AWSTemplateFormatVersion: 2010-09-09
Description: |
  This temp launches an ec2 instance with a SG which enables SSH.
  
Resources:
  CFNInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: guile # Please use your key pair name without pem.
      SecurityGroups:
        - !Ref CFNSecGroup
      Tags:
        - Key: Name
          Value: First-CFN-Instance

  CFNSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enables SSH for CFN Instance # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
          
